services:
  postgres:
    image: postgres:18.1-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - traefik_proxy
    shm_size: 512mb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:8.4-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - traefik_proxy
    command: redis-server --maxmemory ${REDIS_MAX_MEMORY:-256mb} --maxmemory-policy allkeys-lru --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=core.settings.settings
    volumes:
      - static:/app/static
      - media:/app/media
    networks:
      - traefik_proxy
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  rq_worker:
    container_name: rq_worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=core.settings.settings
    command: python manage.py rqworker default
    volumes:
      - static:/app/static
      - media:/app/media
    networks:
      - traefik_proxy
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy

  rq_scheduler:
    container_name: rq_scheduler
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=core.settings.settings
    command: python manage.py rqscheduler
    volumes:
      - static:/app/static
      - media:/app/media
    networks:
      - traefik_proxy
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  static:
  media:

networks:
  traefik_proxy:
    external: true
