# Generated by Django 5.2.7 on 2025-12-22 05:09

import app_video.utils.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('horror', 'Horror')], db_index=True, max_length=64)),
                ('video_file', models.FileField(upload_to=app_video.utils.upload_path.video_upload_path)),
                ('thumbnail', models.ImageField(upload_to=app_video.utils.upload_path.thumbnail_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rq_job_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
