# Generated by Django 5.2.7 on 2026-01-29 11:34

import app_video.utils.upload_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('horror', 'Horror')], db_index=True, max_length=32)),
                ('file', models.FileField(upload_to=app_video.utils.upload_utils.get_slugged_file_path)),
                ('thumbnail', models.ImageField(upload_to=app_video.utils.upload_utils.get_slugged_file_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('converted', 'Converted'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
