# Generated by Django 5.2.7 on 2025-12-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rq_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
